### ISSUE TITLE
EIP-155

### ISSUE THREAD

**Issue by alexcos20** [oceanprotocol/ocean-faucet#1]
With Geth v1.10.0, EIP-155 is enforced (see https://blog.ethereum.org/2021/03/03/geth-v1-10-0/, chapter "ChainID enforcement")

All transactions need to follow https://github.com/ethereum/EIPs/blob/master/EIPS/eip-155.md or they will be rejected in the future (Infura runs v1.10.0, but with --rpc.allow-unprotected-txs, so we are safe for the moment ).

All sending transactions should include chainId as well.

**Comment by bogdanfazakas** [comment]
Tested against a synced Ropsten node with enforced EIP-155, and with the latest web3 library installed send transaction seemed fine, no need to manually add the chainId
